### PR TITLE
changing the file

### PR DESCRIPTION
**Pull request by mhk37**
Added name, github id, discord id and meme

### CODE REVIEW

**Review by iambillmccann — CHANGES_REQUESTED** [review]
In the file web/src/Routes.js please move line 8 (the Route tag to your page) after line 9 (the Set tag)

This is a minor thing, but the table tags in your page should by indented. If you use VSCode, the Prettier extension will do that for you.

**Comment by mhk37** [comment]
Indented and moved line 8 under line 9 in routes.js

**Comment by mhk37** [comment]
there were some merge conflicts that I resolved

**Review by mhk37 — COMMENTED** [review]
done making the changes:  In the file web/src/Routes.js please move line 8 (after line 9 (the Set tag), indented and made my own page

**Comment by mhk37** [comment]
done making the changes

**Review by iambillmccann — APPROVED** [review]

**Pull request merged**
