### PR TITLE
Namitha yalla hw1

### PR DESCRIPTION
**Pull request by nYalla6**

### CODE REVIEW

**Review by iambillmccann — CHANGES_REQUESTED** [review]
You somehow seemed to have gotten your hands on homework #2, which will be the first part of the Redwood tutorial. The assignment for this week is much simpler.

Here are the basic steps for this assignment ...

- Clone cs490-hw1 to your local device
- Create a branch (branch name must be unique)
- Generate a new page; use the command: yarn redwood generate page {yourname}
- Change the file ./web/src/pages/{yourname}/{yourname}.js
   Add your name, GitHub Id, Discord name, and a favorite meme
- Commit your changes
- Push the changed branch to the server
- Create a Pull Request

**Comment by nYalla6** [comment]
Oops! Sorry, I don't really know what hw2 was but I did mess up a little in the beginning, I'm not sure what changes specifically were needed, but I did remove the banner since that wasn't explicity stated in this week's instructions.

**Comment by nYalla6** [comment]
I also undid those other files that were changed to resolve the merge conflicts!

**Comment by nYalla6** [comment]
I undid all of the other files that caused conflicts.

**Review by iambillmccann — CHANGES_REQUESTED** [review]
There are a ton of extra files in this PR that does not belong in our code. This PR should only have changes to Routes.js and the /NamithaYallaPage folder. That will likely be only four files.

I need you to back out all the other changes.

**Pull request closed without merging**
